package br.gasmartins.movies.infra.persistence.entity;

import br.gasmartins.movies.domain.enums.Genre;
import br.gasmartins.movies.infra.persistence.entity.converter.GenreConverter;
import br.gasmartins.movies.infra.persistence.entity.converter.LocalTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.io.Serializable;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

@AllArgsConstructor
@NoArgsConstructor
@Builder(setterPrefix = "with")
@ToString
@Getter
@Setter
@DynamoDBTable(tableName="Movies")
public class MovieEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName="Name")
    private String name;

    @DynamoDBAttribute(attributeName="Genre")
    @DynamoDBTypeConverted(converter = GenreConverter.class)
    private Genre genre;

    @DynamoDBAttribute(attributeName="Year")
    private Integer year;

    @DynamoDBAttribute(attributeName="DirectedBy")
    private String directedBy;

    @DynamoDBTypeConverted(converter = LocalTimeConverter.class)
    @DynamoDBAttribute(attributeName="Duration")
    private LocalTime duration;

    @Singular
    @DynamoDBAttribute(attributeName = "Actors")
    private List<ActorEntity> actors;

}
